-- not so simple user insertion -- this was generated by gemini
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

DO $$
DECLARE
  -- 1. Definimos os UUIDs fixos e fáceis para usar em qualquer lugar do seed
  id_chair     uuid := '11111111-1111-1111-1111-111111111111';
  id_albania   uuid := '22222222-2222-2222-2222-222222222222';
  id_alemanha  uuid := '33333333-3333-3333-3333-333333333333';
  id_brazil    uuid := '44444444-4444-4444-4444-444444444444';
BEGIN

  -- ----------------------------------------------------
  -- INSERÇÃO DOS USUÁRIOS (AUTH)
  -- ----------------------------------------------------
  
  -- Usuário 1: chair
  INSERT INTO auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)
  VALUES (id_chair, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'chair@codelab.usp.br', crypt('password123', gen_salt('bf')), now(), '{"name": "chair"}'::jsonb, now(), now(), '', '', '', '') ON CONFLICT (id) DO NOTHING;
  INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
  VALUES (gen_random_uuid(), id_chair, 'chair@codelab.usp.br', format('{"sub":"%s","email":"chair@codelab.usp.br"}', id_chair)::jsonb, 'email', now(), now(), now()) ON CONFLICT (provider, provider_id) DO NOTHING;

  -- Usuário 2: albania
  INSERT INTO auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)
  VALUES (id_albania, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'albania@codelab.usp.br', crypt('password123', gen_salt('bf')), now(), '{"name": "albania"}'::jsonb, now(), now(), '', '', '', '') ON CONFLICT (id) DO NOTHING;
  INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
  VALUES (gen_random_uuid(), id_albania, 'albania@codelab.usp.br', format('{"sub":"%s","email":"albania@codelab.usp.br"}', id_albania)::jsonb, 'email', now(), now(), now()) ON CONFLICT (provider, provider_id) DO NOTHING;

  -- Usuário 3: alemanha
  INSERT INTO auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)
  VALUES (id_alemanha, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'alemanha@codelab.usp.br', crypt('password123', gen_salt('bf')), now(), '{"name": "alemanha"}'::jsonb, now(), now(), '', '', '', '') ON CONFLICT (id) DO NOTHING;
  INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
  VALUES (gen_random_uuid(), id_alemanha, 'alemanha@codelab.usp.br', format('{"sub":"%s","email":"alemanha@codelab.usp.br"}', id_alemanha)::jsonb, 'email', now(), now(), now()) ON CONFLICT (provider, provider_id) DO NOTHING;

  INSERT INTO auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)
  VALUES (id_brazil, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'brazil@codelab.usp.br', crypt('password123', gen_salt('bf')), now(), '{"name": "brazil"}'::jsonb, now(), now(), '', '', '', '') ON CONFLICT (id) DO NOTHING;
  INSERT INTO auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
  VALUES (gen_random_uuid(), id_brazil, 'brazil@codelab.usp.br', format('{"sub":"%s","email":"brazil@codelab.usp.br"}', id_brazil)::jsonb, 'email', now(), now(), now()) ON CONFLICT (provider, provider_id) DO NOTHING;

END $$;
