sonar.projectKey=uspcodelab_webmun
sonar.organization=uspcodelab


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=webmun
sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file
sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

# additional info
sonar.python.coverage.reportPaths=coverage/backend-coverage.xml
sonar.python.version=3.11
sonar.sources=backend/app,frontend/src
sonar.tests=backend/app/tests
sonar.coverage.exclusions=frontend/src/**
