sonar.projectKey=uspcodelab_webmun
sonar.organization=uspcodelab

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=webmun
sonar.projectVersion=1.0


# additional info
sonar.python.coverage.reportPaths=coverage/backend-coverage.xml
sonar.python.version=3.11

sonar.sources=backend/app,frontend/src
sonar.tests=backend/app/tests
sonar.exclusions=backend/app/tests/**,**/components/ui/**,**/src/components/ui/**

sonar.coverage.exclusions=frontend/src/**
sonar.cpd.exclusions=**/components/ui/**,frontend/src/schemas/types.gen.ts
