# where engine lives
from typing import Callable

from .schemas import SessionEvent, DelegateEvents, ChairEvents
from .manager import SessionLiveState

"""
This will document the flow of states the debates will have. As Well as document an initial engine 

Creating a committee should automatically assign a chair as it's admin. Only Secretariats can create a session for a committee

OPEN_SESSION / SETUP: setup state. Websockets are already made, thus possible events are 
- ChooseDelegation: made from Delegates from a list of possible ones (so a list of possible delegations should be present either in server/frontend)
- EditSetup: chair edits setup such as:
    - extends session: (extends an already made session, or unpause session?)
    - speaking_time
    - can_set_motions (during specific debates)
    - default_state (either GSL or Moderated, should be put later)
    - topics

ChooseDelegation should not be possible anymore (at least not for now)

ROLL_CALL: roll call/ quorum count state. Possible events are:
    - SetVotingChoiceEvent: by Delegate 
    - QuestionEvent
    - Any Chair Event: since most are disruptive

To user, INITIAL_DEBATE and OPEN_GSL should look mostly the same
INITIAL_DEBATE: after roll call, if no agenda is set and/or no speaking time for GSL is set, go to this state. It's an initial speakers list. Possible events are: 
    - Motions: subset - (POSTPONE, END, QUORUM, SETAGEND, SETSPEAKINGTIME) 
    - QuestionEvent
    - Any Chair Event
    - CastVoteEvent 
Queue should not be open to speak. Delegates may only speak in motions

OPEN_GSL: default state in general. Queue is open and automatic and all motions can be made. The topic is defaulted to the first one in the order of agenda_topics and index_topic.
    - In particular, YieldEvent must be enabled and configured.

Specific Debates: (Moderated, Unmoderated, Tour) Queue is not automatic, rather, it now serves as a list that Chair can accept someone.
    - Motions may only be set if set_motions is enabled.
    - In particular, Unmoderated should not have a queue/motions enabled at all, but this may be implemented later 

VOTIING_EXECUTION: may be to vote on a motion or on a specific resolution. Only after the chair enables voting on a motion. 

CLOSED_GSL: after a successfull 'Close Speakers List'. Queue is disabled.

PRE_VOTING: ambiguous state after an "close debate" has either entered as a motion, or "move into voting procedures"

VOTING_PROCEDURES: special case of voting on specific resolution

FINISHED: when topics get empty automatically, or chair decides to close session. may be reverted.

This will give some insight into what should or should not be possible during each event
"""

# Handlers for each event
def handle_submit_motion(state: SessionLiveState, event: SessionEvent, sender: str, is_chair: bool):
    pass

# defines the overall "interface" (as in golang?) for a function to be an EventHandler 
type EventHandler = Callable[
        [SessionLiveState, SessionEvent, str, bool], # overall signature
        SessionLiveState # Return type
        ]

# TODO: check if list has all events, since it's generated by codex
EVENT_HANDLERS: dict[DelegateEvents | ChairEvents, EventHandler] = {
      DelegateEvents.SUBMIT_MOTION: handle_submit_motion,
      DelegateEvents.SUBMIT_QUESTION: handle_submit_question,
      DelegateEvents.JOIN_QUEUE: handle_join_queue,
      DelegateEvents.LEAVE_QUEUE: handle_leave_queue,
      DelegateEvents.CAST_VOTE: handle_cast_vote,
      DelegateEvents.CHOOSE_DELEGATION: handle_choose_delegation,

      ChairEvents.MANUAL_PHASE_SET: handle_set_phase,
      ChairEvents.TOGGLE_TIMER: handle_toggle_timer,
      ChairEvents.SET_VOTING_STATE: handle_set_voting,
      ChairEvents.RESOLVE_MOTION: handle_resolve_motion,
}

class SimulationEngine:
    # function to calculate new state over old one
    def dispatch(self, 
                 state: SessionLiveState,
                 event: SessionEvent,
                 sender: str, 
                 is_chair: bool) -> SessionLiveState:
         

"""
    def _generate_next_motion_id(self, state: SessionLiveState) -> int:
        if not hasattr(state, "_motion_id_counter"):
            state._motion_id_counter = 0
        state._motion_id_counter += 1
        return state._motion_id_counter

    def _generate_next_question_id(self, state: SessionLiveState) -> int:
        if not hasattr(state, "_question_id_counter"):
            state._question_id_counter = 0
        state._question_id_counter += 1
        return state._question_id_counter

"""
