// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_create_commitee_committees__post
 */
export type BodyCreateCommiteeCommitteesPost = {
    committeeInfo: SessionCreationSchema;
    /**
     * Test
     */
    test: SubmitMotionEvent | SubmitQuestionEvent | CastVoteEvent | ChooseDelegateEvent | SetQueueEvent | YieldEvent | SetSessionEvent | ToggleTimerEvent | IncreaseTimerEvent | SetVotingEvent | ResolveMotionEvent | SpeakerEvent | SetAgendaEvent | SetPhaseEvent;
};

/**
 * CastVoteEvent
 */
export type CastVoteEvent = {
    /**
     * Type
     */
    type: 'CastVoteEvent';
    payload: DelegateVotingPayload;
};

/**
 * ChairForceSpeakerPayload
 */
export type ChairForceSpeakerPayload = {
    /**
     * Speaker
     */
    speaker?: string | null;
    /**
     * Seconds
     */
    seconds?: number | null;
};

/**
 * ChairIncreaseTimerPayload
 */
export type ChairIncreaseTimerPayload = {
    /**
     * Duration Seconds
     */
    duration_seconds?: number;
};

/**
 * ChairResolveMotionPayload
 */
export type ChairResolveMotionPayload = {
    /**
     * Motion Id
     */
    motion_id: number;
    /**
     * Action
     */
    action: 'ACCEPT' | 'DENY';
};

/**
 * ChairSetAgendaPayload
 */
export type ChairSetAgendaPayload = {
    /**
     * Agenda
     */
    agenda: Array<string>;
};

/**
 * ChairSetPhasePayload
 */
export type ChairSetPhasePayload = {
    target_phase: States;
};

/**
 * ChairSetVotingPayload
 */
export type ChairSetVotingPayload = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Majority
     */
    majority: 'SIMPLE' | 'QUALIFIED' | 'ABSOLUTE';
    /**
     * Veto Power
     */
    veto_power: boolean;
};

/**
 * ChairToggleTimerPayload
 */
export type ChairToggleTimerPayload = {
    /**
     * Toggle
     */
    toggle?: boolean;
};

/**
 * ChooseDelegateEvent
 */
export type ChooseDelegateEvent = {
    /**
     * Type
     */
    type: 'ChooseDelegateEvent';
    payload: ChooseDelegatePayload;
};

/**
 * ChooseDelegatePayload
 */
export type ChooseDelegatePayload = {
    /**
     * Choice
     */
    choice: string;
};

/**
 * DelegateMotionPayload
 */
export type DelegateMotionPayload = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Priority
     */
    priority?: number;
    type: Motions;
    /**
     * Delegate
     */
    delegate?: number | null;
    /**
     * Total Duration Minutes
     */
    total_duration_minutes?: number | null;
    /**
     * Total Speaking Seconds
     */
    total_speaking_seconds?: number | null;
    /**
     * Target Topic
     */
    target_topic?: string | null;
    /**
     * Details
     */
    details?: string | null;
};

/**
 * DelegateQuestionPayload
 */
export type DelegateQuestionPayload = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Priority
     */
    priority?: number;
    type: Questions;
    /**
     * Delegate
     */
    delegate?: number | null;
    /**
     * Details
     */
    details: string;
};

/**
 * DelegateVotingPayload
 */
export type DelegateVotingPayload = {
    /**
     * Motion Id
     */
    motion_id: number;
    /**
     * Vote
     */
    vote: 'FAVOUR' | 'AGAINST' | 'ABSTAIN';
};

/**
 * DelegateYieldPayload
 */
export type DelegateYieldPayload = {
    /**
     * Choice
     */
    choice?: string | 'CHAIR';
};

/**
 * EmptyPayload
 */
export type EmptyPayload = {
    [key: string]: unknown;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IncreaseTimerEvent
 */
export type IncreaseTimerEvent = {
    /**
     * Type
     */
    type: 'IncreaseTimerEvent';
    payload: ChairIncreaseTimerPayload;
};

/**
 * Motions
 */
export const Motions = {
    CHANGE_DEBATE_TYPE: 'Change Debate Type',
    POSTPONE_SESSION: 'Postpone Session',
    REOPEN_SESSION: 'Reopen Session',
    TOUR_DE_TABLE: 'Tour de Table',
    END_DEBATE: 'End Debate',
    VOTE_AMENDMENT: 'Vote Amendment',
    VOTE_BY_ROLL_CALL: 'Vote by Roll Call',
    CLOSE_SPEAKERS_LIST: 'Close Speakers list',
    REOPEN_SPEAKERS_LIST: 'Reopen Speakers list',
    SPLIT_PROPOSAL: 'Split Proposal',
    INTRODUCE_RESOLUTION_PROPOSAL: 'Introduce Resolution Proposal',
    INTRODUCE_AMENDMENT_PROPOSAL: 'Introduce Amendment Proposal',
    CHANGE_TOPIC: 'Change Topic',
    QUORUM: 'Quorum',
    '': ''
} as const;

/**
 * Motions
 */
export type Motions = typeof Motions[keyof typeof Motions];

/**
 * Questions
 */
export const Questions = {
    ORDER: 'Order',
    QUESTION: 'Question',
    PERSONAL_PRIVILEGE: 'Personal Privilege'
} as const;

/**
 * Questions
 */
export type Questions = typeof Questions[keyof typeof Questions];

/**
 * ResolveMotionEvent
 */
export type ResolveMotionEvent = {
    /**
     * Type
     */
    type: 'ResolveMotionEvent';
    payload: ChairResolveMotionPayload;
};

/**
 * SessionCreationSchema
 */
export type SessionCreationSchema = {
    /**
     * Committee Id
     */
    committee_id: number;
    /**
     * Name
     */
    name: string;
};

/**
 * SetAgendaEvent
 */
export type SetAgendaEvent = {
    /**
     * Type
     */
    type: 'SetAgendaEvent';
    payload: ChairSetAgendaPayload;
};

/**
 * SetPhaseEvent
 */
export type SetPhaseEvent = {
    /**
     * Type
     */
    type: 'SetPhaseEvent';
    payload: ChairSetPhasePayload;
};

/**
 * SetQueueEvent
 */
export type SetQueueEvent = {
    /**
     * Type
     */
    type: 'Join Speakers Queue' | 'Leave Speakers Queue';
    /**
     * Payload
     */
    payload?: {
        [key: string]: unknown;
    };
};

/**
 * SetSessionEvent
 */
export type SetSessionEvent = {
    /**
     * Type
     */
    type: 'Open Session' | 'Close Session';
    payload: EmptyPayload;
};

/**
 * SetVotingEvent
 */
export type SetVotingEvent = {
    /**
     * Type
     */
    type: 'SetVotingEvent';
    payload: ChairSetVotingPayload;
};

/**
 * SpeakerEvent
 */
export type SpeakerEvent = {
    /**
     * Type
     */
    type: 'SpeakerEvent';
    payload: ChairForceSpeakerPayload;
};

/**
 * States
 */
export const States = {
    SETUP_ROOM: 'Setup Room',
    ROLL_CALL: 'Roll Call',
    INITIAL_DEBATE: 'Initial Debate',
    OPEN_GSL: 'Open GSL',
    CLOSED_GSL: 'Closed GSL',
    VOTING_PROCEDURES: 'Voting Procedures',
    FINISHED: 'Finished',
    MODERATED_CAUCUS: 'Moderated Caucus',
    UNMODERATED_CAUCUS: 'Unmoderated Caucus',
    VOTING_EXECUTION: 'Voting Execution',
    PRE_VOTING: 'Pre-voting'
} as const;

/**
 * States
 */
export type States = typeof States[keyof typeof States];

/**
 * SubmitMotionEvent
 */
export type SubmitMotionEvent = {
    /**
     * Type
     */
    type: 'SubmitMotionEvent';
    payload: DelegateMotionPayload;
};

/**
 * SubmitQuestionEvent
 */
export type SubmitQuestionEvent = {
    /**
     * Type
     */
    type: 'SubmitQuestionEvent';
    payload: DelegateQuestionPayload;
};

/**
 * ToggleTimerEvent
 */
export type ToggleTimerEvent = {
    /**
     * Type
     */
    type: 'ToggleTimerEvent';
    payload: ChairToggleTimerPayload;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * YieldEvent
 */
export type YieldEvent = {
    /**
     * Type
     */
    type: 'YieldEvent';
    payload: DelegateYieldPayload;
};

export type CreateCommiteeCommitteesPostData = {
    body: BodyCreateCommiteeCommitteesPost;
    path?: never;
    query?: never;
    url: '/committees/';
};

export type CreateCommiteeCommitteesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCommiteeCommitteesPostError = CreateCommiteeCommitteesPostErrors[keyof CreateCommiteeCommitteesPostErrors];

export type CreateCommiteeCommitteesPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type CreateCommiteeCommitteesPostResponse = CreateCommiteeCommitteesPostResponses[keyof CreateCommiteeCommitteesPostResponses];
