// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AnswerRollCallEvent
 */
export type AnswerRollCallEvent = {
    /**
     * Type
     */
    type: 'AnswerRollCallEvent';
    payload: AnswerRollCallPayload;
};

/**
 * AnswerRollCallPayload
 */
export type AnswerRollCallPayload = {
    /**
     * Choice
     */
    choice: 'Present' | 'Present and Voting';
};

/**
 * Body_dummy_committees_dummy_get
 */
export type BodyDummyCommitteesDummyGet = {
    /**
     * Name
     */
    name: SubmitMotionEvent | SubmitQuestionEvent | CastVoteEvent | ChooseDelegateEvent | AnswerRollCallEvent | JoinQueueEvent | LeaveQueueEvent | OpenSessionEvent | CloseSessionEvent | IncreaseTimerEvent | ToggleTimerEvent | OpenInformalVotingEvent | CloseProceduralVotingEvent | CloseInformalVotingEvent | ResolveMotionEvent | SpeakerEvent | SetAgendaEvent | SetPhaseEvent | MarkRollCallEvent | CloseRollCallEvent | ChairInsertQueueEvent | MarkRollCallBulkEvent;
    schemas: SessionLiveState;
};

/**
 * CastVoteEvent
 */
export type CastVoteEvent = {
    /**
     * Type
     */
    type: 'CastVoteEvent';
    payload: DelegateVotingPayload;
};

/**
 * ChairCloseInformalVotingPayload
 */
export type ChairCloseInformalVotingPayload = {
    /**
     * Voting Id
     */
    voting_id?: number | null;
};

/**
 * ChairEvents
 */
export const ChairEvents = {
    OPEN_SESSION_EVENT: 'OpenSessionEvent',
    TOGGLE_TIMER_EVENT: 'ToggleTimerEvent',
    INCREASE_TIMER_EVENT: 'IncreaseTimerEvent',
    OPEN_INFORMAL_VOTING_EVENT: 'OpenInformalVotingEvent',
    RESOLVE_MOTION_EVENT: 'ResolveMotionEvent',
    CLOSE_PROCEDURAL_VOTING_EVENT: 'CloseProceduralVotingEvent',
    CLOSE_INFORMAL_VOTING_EVENT: 'CloseInformalVotingEvent',
    SET_AGENDA_EVENT: 'SetAgendaEvent',
    SET_PHASE_EVENT: 'SetPhaseEvent',
    CLOSE_SESSION_EVENT: 'CloseSessionEvent',
    SPEAKER_EVENT: 'SpeakerEvent',
    MARK_ROLL_CALL_EVENT: 'MarkRollCallEvent',
    MARK_ROLL_CALL_BULK_EVENT: 'Mark Roll Call Bulk Event',
    CLOSE_ROLL_CALL_EVENT: 'CloseRollCallEvent',
    INSERT_QUEUE_EVENT: 'InsertQueueEvent'
} as const;

/**
 * ChairEvents
 */
export type ChairEvents = typeof ChairEvents[keyof typeof ChairEvents];

/**
 * ChairForceSpeakerPayload
 */
export type ChairForceSpeakerPayload = {
    /**
     * Speaker
     */
    speaker?: string | null;
    /**
     * Seconds
     */
    seconds?: number | null;
};

/**
 * ChairIncreaseTimerPayload
 */
export type ChairIncreaseTimerPayload = {
    /**
     * Seconds
     */
    seconds?: number;
};

/**
 * ChairInsertQueueEvent
 */
export type ChairInsertQueueEvent = {
    /**
     * Type
     */
    type: 'InsertQueueEvent';
    payload: ChairInsertQueuePayload;
};

/**
 * ChairInsertQueuePayload
 */
export type ChairInsertQueuePayload = {
    /**
     * Target
     */
    target: number;
};

/**
 * ChairOpenInformalVotingPayload
 */
export type ChairOpenInformalVotingPayload = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Majority
     */
    majority: 'SIMPLE' | 'QUALIFIED' | 'ABSOLUTE';
    /**
     * Veto Power
     */
    veto_power: boolean;
};

/**
 * ChairResolveMotionPayload
 */
export type ChairResolveMotionPayload = {
    /**
     * Motion Id
     */
    motion_id: number;
    /**
     * Action
     */
    action: 'ACCEPT' | 'DENY';
};

/**
 * ChairSetAgendaPayload
 */
export type ChairSetAgendaPayload = {
    /**
     * Agenda
     */
    agenda: Array<string>;
};

/**
 * ChairSetPhasePayload
 */
export type ChairSetPhasePayload = {
    target_phase: States;
};

/**
 * ChairToggleTimerPayload
 */
export type ChairToggleTimerPayload = {
    /**
     * Toggle
     */
    toggle?: boolean;
};

/**
 * ChooseDelegateEvent
 */
export type ChooseDelegateEvent = {
    /**
     * Type
     */
    type: 'ChooseDelegateEvent';
    payload: ChooseDelegatePayload;
};

/**
 * ChooseDelegatePayload
 */
export type ChooseDelegatePayload = {
    /**
     * Choice
     */
    choice: string;
};

/**
 * CloseInformalVotingEvent
 */
export type CloseInformalVotingEvent = {
    /**
     * Type
     */
    type: 'CloseInformalVotingEvent';
    payload: ChairCloseInformalVotingPayload;
};

/**
 * CloseProceduralVotingEvent
 */
export type CloseProceduralVotingEvent = {
    /**
     * Type
     */
    type: 'CloseProceduralVotingEvent';
    payload: EmptyPayload;
};

/**
 * CloseRollCallEvent
 */
export type CloseRollCallEvent = {
    /**
     * Type
     */
    type: 'CloseRollCallEvent';
    payload: EmptyPayload;
};

/**
 * CloseSessionEvent
 */
export type CloseSessionEvent = {
    /**
     * Type
     */
    type: 'CloseSessionEvent';
    payload: EmptyPayload;
};

/**
 * DebateContext
 */
export type DebateContext = {
    debate_type: DebateTypes;
    return_state: States;
    /**
     * Total Duration Seconds
     */
    total_duration_seconds?: number | null;
    /**
     * Total Speeches
     */
    total_speeches?: number | null;
    /**
     * Per Speaker Seconds
     */
    per_speaker_seconds?: number | null;
    /**
     * Expires At
     */
    expires_at?: string | null;
    /**
     * Topic
     */
    topic?: string | null;
};

/**
 * DebateTypes
 */
export const DebateTypes = {
    SPEAKERS_LIST: 'Speakers List',
    MODERATED_DEBATE: 'Moderated Debate',
    UNMODERATED_DEBATE: 'Unmoderated Debate'
} as const;

/**
 * DebateTypes
 */
export type DebateTypes = typeof DebateTypes[keyof typeof DebateTypes];

/**
 * DelegateEvents
 */
export const DelegateEvents = {
    SUBMIT_MOTION_EVENT: 'SubmitMotionEvent',
    SUBMIT_QUESTION_EVENT: 'SubmitQuestionEvent',
    JOIN_QUEUE_EVENT: 'JoinQueueEvent',
    LEAVE_QUEUE_EVENT: 'LeaveQueueEvent',
    CAST_VOTE_EVENT: 'CastVoteEvent',
    CHOOSE_DELEGATE_EVENT: 'ChooseDelegateEvent',
    YIELD_EVENT: 'YieldEvent',
    ANSWER_ROLL_CALL_EVENT: 'AnswerRollCallEvent'
} as const;

/**
 * DelegateEvents
 */
export type DelegateEvents = typeof DelegateEvents[keyof typeof DelegateEvents];

/**
 * DelegateMotionPayload
 */
export type DelegateMotionPayload = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Priority
     */
    priority?: number;
    type: Motions;
    delegate?: Delegation | null;
    debate_type?: DebateTypes | null;
    /**
     * Total Duration Minutes
     */
    total_duration_minutes?: number | null;
    /**
     * Per Speaker Seconds
     */
    per_speaker_seconds?: number | null;
    /**
     * Target Topic
     */
    target_topic?: string | null;
    /**
     * Details
     */
    details?: string | null;
};

/**
 * DelegateQuestionPayload
 */
export type DelegateQuestionPayload = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Priority
     */
    priority?: number;
    type: Questions;
    delegate?: Delegation | null;
    /**
     * Details
     */
    details: string;
};

/**
 * DelegateVotingPayload
 */
export type DelegateVotingPayload = {
    /**
     * Type
     */
    type: 'FORMAL' | 'INFORMAL';
    /**
     * Motion Id
     */
    motion_id?: number | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Vote
     */
    vote: 'FAVOUR' | 'AGAINST' | 'ABSTAIN';
};

/**
 * Delegation
 */
export type Delegation = {
    /**
     * Id
     */
    id: number;
    /**
     * Seat
     */
    seat: string;
    /**
     * Name
     */
    name: string;
    /**
     * Code
     */
    code: string;
};

/**
 * EmptyPayload
 */
export type EmptyPayload = {
    [key: string]: unknown;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IncreaseTimerEvent
 */
export type IncreaseTimerEvent = {
    /**
     * Type
     */
    type: 'IncreaseTimerEvent';
    payload: ChairIncreaseTimerPayload;
};

/**
 * JoinQueueEvent
 */
export type JoinQueueEvent = {
    /**
     * Type
     */
    type: 'JoinQueueEvent';
    /**
     * Payload
     */
    payload?: {
        [key: string]: unknown;
    };
};

/**
 * LeaveQueueEvent
 */
export type LeaveQueueEvent = {
    /**
     * Type
     */
    type: 'LeaveQueueEvent';
    /**
     * Payload
     */
    payload?: {
        [key: string]: unknown;
    };
};

/**
 * MarkRollCallBulkEvent
 */
export type MarkRollCallBulkEvent = {
    /**
     * Type
     */
    type: 'Mark Roll Call Bulk Event';
    payload: MarkRollCallBulkPayload;
};

/**
 * MarkRollCallBulkPayload
 */
export type MarkRollCallBulkPayload = {
    /**
     * Rollcalls
     */
    Rollcalls: {
        [key: string]: RollCallChoice;
    };
};

/**
 * MarkRollCallEvent
 */
export type MarkRollCallEvent = {
    /**
     * Type
     */
    type: 'MarkRollCallEvent';
    payload: MarkRollCallPayload;
};

/**
 * MarkRollCallPayload
 */
export type MarkRollCallPayload = {
    /**
     * Delegation Id
     */
    delegation_id: number;
    choice: RollCallChoice;
};

/**
 * Motions
 */
export const Motions = {
    CHANGE_DEBATE_TYPE: 'Change Debate Type',
    POSTPONE_SESSION: 'Postpone Session',
    REOPEN_SESSION: 'Reopen Session',
    TOUR_DE_TABLE: 'Tour de Table',
    END_DEBATE: 'End Debate',
    VOTE_AMENDMENT: 'Vote Amendment',
    VOTE_BY_ROLL_CALL: 'Vote by Roll Call',
    CLOSE_SPEAKERS_LIST: 'Close Speakers list',
    REOPEN_SPEAKERS_LIST: 'Reopen Speakers list',
    SPLIT_PROPOSAL: 'Split Proposal',
    INTRODUCE_RESOLUTION_PROPOSAL: 'Introduce Resolution Proposal',
    INTRODUCE_AMENDMENT_PROPOSAL: 'Introduce Amendment Proposal',
    CHANGE_TOPIC: 'Change Topic',
    QUORUM: 'Quorum',
    '': ''
} as const;

/**
 * Motions
 */
export type Motions = typeof Motions[keyof typeof Motions];

/**
 * OpenInformalVotingEvent
 */
export type OpenInformalVotingEvent = {
    /**
     * Type
     */
    type: 'OpenInformalVotingEvent';
    payload: ChairOpenInformalVotingPayload;
};

/**
 * OpenSessionEvent
 */
export type OpenSessionEvent = {
    /**
     * Type
     */
    type: 'OpenSessionEvent';
    payload: EmptyPayload;
};

/**
 * Questions
 */
export const Questions = {
    ORDER: 'Order',
    QUESTION: 'Question',
    PERSONAL_PRIVILEGE: 'Personal Privilege'
} as const;

/**
 * Questions
 */
export type Questions = typeof Questions[keyof typeof Questions];

/**
 * ResolveMotionEvent
 */
export type ResolveMotionEvent = {
    /**
     * Type
     */
    type: 'ResolveMotionEvent';
    payload: ChairResolveMotionPayload;
};

/**
 * RollCallChoice
 */
export const RollCallChoice = {
    PRESENT: 'Present',
    PRESENT_AND_VOTING: 'Present and Voting',
    ABSENT: 'Absent'
} as const;

/**
 * RollCallChoice
 */
export type RollCallChoice = typeof RollCallChoice[keyof typeof RollCallChoice];

/**
 * RollCallContext
 */
export type RollCallContext = {
    /**
     * Registry
     */
    registry?: {
        [key: string]: RollCallChoice;
    };
    current_delegation?: Delegation | null;
};

/**
 * SessionCreationSchema
 */
export type SessionCreationSchema = {
    /**
     * Session Id
     */
    session_id: number;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Delegations
     */
    delegations: Array<Delegation>;
};

/**
 * SessionLiveState
 */
export type SessionLiveState = {
    /**
     * Session Id
     */
    session_id: number;
    /**
     * Start Time
     */
    start_time: string;
    /**
     * Delegations
     */
    delegations: Array<Delegation>;
    current_state?: States;
    /**
     * Timer Is Running
     */
    timer_is_running?: boolean;
    /**
     * Timer Expiration
     */
    timer_expiration?: string | null;
    /**
     * Timer Remaining Seconds
     */
    timer_remaining_seconds?: number;
    current_speaker?: Delegation | null;
    /**
     * Gsl Queue
     */
    gsl_queue?: Array<Delegation>;
    /**
     * Can Set Motion
     */
    can_set_motion?: boolean;
    /**
     * Gsl Default Time Seconds
     */
    gsl_default_time_seconds?: number;
    /**
     * Caucus List
     */
    caucus_list?: Array<Delegation>;
    debate?: DebateContext | null;
    /**
     * Submitted Motions
     */
    submitted_motions?: Array<DelegateMotionPayload>;
    /**
     * Submitted Questions
     */
    submitted_questions?: Array<DelegateQuestionPayload>;
    /**
     * Agenda Topics
     */
    agenda_topics?: Array<[
        string,
        boolean
    ]>;
    /**
     * Active Topic Index
     */
    active_topic_index?: number | null;
    voting?: VotingContext | null;
    /**
     * Voting Choice
     */
    voting_choice?: {
        [key: string]: RollCallChoice;
    } | null;
    roll_call: RollCallContext;
};

/**
 * SetAgendaEvent
 */
export type SetAgendaEvent = {
    /**
     * Type
     */
    type: 'SetAgendaEvent';
    payload: ChairSetAgendaPayload;
};

/**
 * SetPhaseEvent
 */
export type SetPhaseEvent = {
    /**
     * Type
     */
    type: 'SetPhaseEvent';
    payload: ChairSetPhasePayload;
};

/**
 * SpeakerEvent
 */
export type SpeakerEvent = {
    /**
     * Type
     */
    type: 'SpeakerEvent';
    payload: ChairForceSpeakerPayload;
};

/**
 * States
 */
export const States = {
    SETUP_ROOM: 'Setup Room',
    ROLL_CALL: 'Roll Call',
    INITIAL_DEBATE: 'Initial Debate',
    OPEN_GSL: 'Open GSL',
    CLOSED_GSL: 'Closed GSL',
    VOTING_PREPARATION: 'Voting Preparation',
    VOTING_PROCEDURES: 'Voting Procedures',
    FINISHED: 'Finished',
    MODERATED_CAUCUS: 'Moderated Caucus',
    UNMODERATED_CAUCUS: 'Unmoderated Caucus',
    VOTING_EXECUTION: 'Voting Execution',
    BETWEEN_DEBATES: 'Between Debates'
} as const;

/**
 * States
 */
export type States = typeof States[keyof typeof States];

/**
 * SubmitMotionEvent
 */
export type SubmitMotionEvent = {
    /**
     * Type
     */
    type: 'SubmitMotionEvent';
    payload: DelegateMotionPayload;
};

/**
 * SubmitQuestionEvent
 */
export type SubmitQuestionEvent = {
    /**
     * Type
     */
    type: 'SubmitQuestionEvent';
    payload: DelegateQuestionPayload;
};

/**
 * ToggleTimerEvent
 */
export type ToggleTimerEvent = {
    /**
     * Type
     */
    type: 'ToggleTimerEvent';
    payload: ChairToggleTimerPayload;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VotingContext
 */
export type VotingContext = {
    /**
     * Target Type
     */
    target_type: 'PROCEDURAL' | 'SUBSTANTIVE' | 'INFORMAL';
    motion_in_vote?: DelegateMotionPayload | null;
    /**
     * Title
     */
    title?: string | null;
    return_state: States;
    /**
     * Voting Registry
     */
    voting_registry?: {
        [key: string]: 'FAVOUR' | 'AGAINST' | 'ABSTAIN';
    };
    /**
     * Majority
     */
    majority: 'SIMPLE' | 'QUALIFIED' | 'ABSOLUTE';
    /**
     * Veto Power
     */
    veto_power: boolean;
};

export type DummyCommitteesDummyGetData = {
    body: BodyDummyCommitteesDummyGet;
    path?: never;
    query: {
        enum1: DelegateEvents;
        enum2: ChairEvents;
    };
    url: '/committees/dummy';
};

export type DummyCommitteesDummyGetErrors = {
    /**
     * Successful Response
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DummyCommitteesDummyGetError = DummyCommitteesDummyGetErrors[keyof DummyCommitteesDummyGetErrors];

export type CreateSessionEndpointCommitteesPostData = {
    body: SessionCreationSchema;
    path?: never;
    query?: never;
    url: '/committees/';
};

export type CreateSessionEndpointCommitteesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSessionEndpointCommitteesPostError = CreateSessionEndpointCommitteesPostErrors[keyof CreateSessionEndpointCommitteesPostErrors];

export type CreateSessionEndpointCommitteesPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type CreateSessionEndpointCommitteesPostResponse = CreateSessionEndpointCommitteesPostResponses[keyof CreateSessionEndpointCommitteesPostResponses];
