// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AccessibleCommittee
 */
export type AccessibleCommittee = {
    /**
     * Committee Id
     */
    committee_id: number;
    /**
     * Role
     */
    role: string;
    /**
     * Representation Id
     */
    representation_id: number | null;
};

/**
 * CommitteeCreate
 */
export type CommitteeCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * CommitteeRead
 */
export type CommitteeRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Conference Id
     */
    conference_id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CommitteeScopedConferenceRole
 */
export type CommitteeScopedConferenceRole = {
    /**
     * Committee Id
     */
    committee_id: number;
    /**
     * Role
     */
    role: string;
};

/**
 * ConferenceAccess
 */
export type ConferenceAccess = {
    /**
     * Conference Id
     */
    conference_id: number;
    /**
     * Roles
     */
    roles: Array<string>;
    /**
     * Committee Roles
     */
    committee_roles: Array<CommitteeScopedConferenceRole>;
    /**
     * Accessible Committees
     */
    accessible_committees: Array<AccessibleCommittee>;
    /**
     * Can Manage Conference
     */
    can_manage_conference: boolean;
};

/**
 * ConferenceCreate
 */
export type ConferenceCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Location
     */
    location?: string | null;
    /**
     * Logo Url
     */
    logo_url?: string | null;
    /**
     * Theme Color
     */
    theme_color?: string | null;
    /**
     * Start Date
     */
    start_date?: string | null;
    /**
     * End Date
     */
    end_date?: string | null;
};

/**
 * ConferenceRead
 */
export type ConferenceRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: string;
    /**
     * Owner Id
     */
    owner_id: string | null;
    /**
     * Location
     */
    location: string | null;
    /**
     * Logo Url
     */
    logo_url: string | null;
    /**
     * Theme Color
     */
    theme_color: string | null;
    /**
     * Start Date
     */
    start_date: string | null;
    /**
     * End Date
     */
    end_date: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * SessionCreationSchema
 *
 * Schema to create a session. Follows a DB schema + extra configs format
 */
export type SessionCreationSchema = {
    /**
     * Committee Id
     */
    committee_id: number;
    /**
     * Name
     */
    name?: string | null;
};

/**
 * SessionRepresentation
 */
export type SessionRepresentation = {
    role: SessionRoles;
    /**
     * Representation Id
     */
    representation_id: number | null;
};

/**
 * SessionRoles
 */
export const SessionRoles = { CHAIR: 'chair', DELEGATE: 'delegate' } as const;

/**
 * SessionRoles
 */
export type SessionRoles = typeof SessionRoles[keyof typeof SessionRoles];

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * ChairEvents
 */
export const ChairEvents = {
    OPEN_SESSION_EVENT: 'OpenSessionEvent',
    TOGGLE_TIMER_EVENT: 'ToggleTimerEvent',
    INCREASE_TIMER_EVENT: 'IncreaseTimerEvent',
    OPEN_INFORMAL_VOTING_EVENT: 'OpenInformalVotingEvent',
    RESOLVE_MOTION_EVENT: 'ResolveMotionEvent',
    LOG_MOTION_EVENT: 'LogMotionEvent',
    CLOSE_PROCEDURAL_VOTING_EVENT: 'CloseProceduralVotingEvent',
    CLOSE_INFORMAL_VOTING_EVENT: 'CloseInformalVotingEvent',
    FINISH_CAUCUS_EVENT: 'FinishCaucusEvent',
    SET_PHASE_EVENT: 'SetPhaseEvent',
    CLOSE_SESSION_EVENT: 'CloseSessionEvent',
    SET_AGENDA_ITEM_EVENT: 'SetAgendaItemEvent',
    MARK_AGENDA_ITEM_EVENT: 'MarkAgendaItemEvent',
    DELETE_AGENDA_ITEM_EVENT: 'DeleteAgendaItemEvent',
    SET_AGENDA: 'SetAgenda',
    NEXT_SPEAKER_EVENT: 'NextSpeakerEvent',
    ADD_GSL_SPEAKER_EVENT: 'AddGslSpeakerEvent',
    GRANT_FLOOR_EVENT: 'GrantFloorEvent',
    CEDE_TIME_EVENT: 'CedeTimeEvent',
    END_SPEECH_EVENT: 'EndSpeechEvent',
    MARK_ROLL_CALL_EVENT: 'MarkRollCallEvent',
    MARK_ROLL_CALL_BULK_EVENT: 'MarkRollCallBulkEvent',
    CLOSE_ROLL_CALL_EVENT: 'CloseRollCallEvent'
} as const;

/**
 * ChairEvents
 */
export type ChairEvents = typeof ChairEvents[keyof typeof ChairEvents];

/**
 * DelegateEvents
 */
export const DelegateEvents = {
    SUBMIT_MOTION_EVENT: 'SubmitMotionEvent',
    SUBMIT_QUESTION_EVENT: 'SubmitQuestionEvent',
    JOIN_QUEUE_EVENT: 'JoinQueueEvent',
    LEAVE_QUEUE_EVENT: 'LeaveQueueEvent',
    CAST_VOTE_EVENT: 'CastVoteEvent',
    YIELD_EVENT: 'YieldEvent',
    ANSWER_ROLL_CALL_EVENT: 'AnswerRollCallEvent'
} as const;

/**
 * DelegateEvents
 */
export type DelegateEvents = typeof DelegateEvents[keyof typeof DelegateEvents];

/**
 * AddGslSpeakerEvent
 */
export type AddGslSpeakerEvent = {
    /**
     * Type
     */
    type: 'AddGslSpeakerEvent';
    payload: AddGslSpeakerPayload;
};

/**
 * AddGslSpeakerPayload
 */
export type AddGslSpeakerPayload = {
    /**
     * Representation Id
     */
    representation_id: number;
};

/**
 * AnswerRollCallEvent
 */
export type AnswerRollCallEvent = {
    /**
     * Type
     */
    type: 'AnswerRollCallEvent';
    payload: AnswerRollCallPayload;
};

/**
 * AnswerRollCallPayload
 */
export type AnswerRollCallPayload = {
    /**
     * Choice
     */
    choice: 'Present' | 'Present and Voting';
};

/**
 * CastVoteEvent
 */
export type CastVoteEvent = {
    /**
     * Type
     */
    type: 'CastVoteEvent';
    payload: DelegateVotingPayload;
};

/**
 * CedeTimeEvent
 */
export type CedeTimeEvent = {
    /**
     * Type
     */
    type: 'CedeTimeEvent';
    payload: CedeTimePayload;
};

/**
 * CedeTimePayload
 */
export type CedeTimePayload = {
    /**
     * Representation Id
     */
    representation_id: number;
};

/**
 * ChairIncreaseTimerPayload
 */
export type ChairIncreaseTimerPayload = {
    /**
     * Seconds
     */
    seconds?: number;
};

/**
 * ChairMotionPayload
 *
 * Extended payload for motions. Used to log motions
 */
export type ChairMotionPayload = {
    type: Motions;
    debate_type?: DebateTypes | null;
    /**
     * Total Duration Minutes
     */
    total_duration_minutes?: number | null;
    /**
     * Per Speaker Seconds
     */
    per_speaker_seconds?: number | null;
    /**
     * Target Topic
     */
    target_topic?: string | null;
    /**
     * Details
     */
    details?: string | null;
    /**
     * Representation Id
     */
    representation_id: number;
    decision: MotionDecision;
};

/**
 * ChairOpenInformalVotingPayload
 */
export type ChairOpenInformalVotingPayload = {
    /**
     * Title
     */
    title?: string | null;
    majority: MajorityTypes;
    /**
     * Veto Power
     */
    veto_power: boolean;
};

/**
 * ChairResolveMotionPayload
 */
export type ChairResolveMotionPayload = {
    /**
     * Motion Id
     */
    motion_id: number;
    /**
     * Action
     */
    action: boolean;
};

/**
 * ChairSetAgendaPayload
 */
export type ChairSetAgendaPayload = {
    /**
     * Agenda
     */
    agenda: Array<string>;
};

/**
 * ChairSetPhasePayload
 */
export type ChairSetPhasePayload = {
    target_phase: States;
};

/**
 * ChairToggleTimerPayload
 */
export type ChairToggleTimerPayload = {
    /**
     * Toggle
     */
    toggle?: boolean;
};

/**
 * CloseInformalVotingEvent
 */
export type CloseInformalVotingEvent = {
    /**
     * Type
     */
    type: 'CloseInformalVotingEvent';
    payload: EmptyPayload;
};

/**
 * CloseProceduralVotingEvent
 */
export type CloseProceduralVotingEvent = {
    /**
     * Type
     */
    type: 'CloseProceduralVotingEvent';
    payload: EmptyPayload;
};

/**
 * CloseRollCallEvent
 */
export type CloseRollCallEvent = {
    /**
     * Type
     */
    type: 'CloseRollCallEvent';
    payload: EmptyPayload;
};

/**
 * CloseSessionEvent
 */
export type CloseSessionEvent = {
    /**
     * Type
     */
    type: 'CloseSessionEvent';
    payload: EmptyPayload;
};

/**
 * DebateTypes
 */
export const DebateTypes = {
    LISTA_DE_DISCURSOS: 'Lista de Discursos',
    DEBATE_MODERADO: 'Debate Moderado',
    DEBATE_NÃO_MODERADO: 'Debate não Moderado'
} as const;

/**
 * DebateTypes
 */
export type DebateTypes = typeof DebateTypes[keyof typeof DebateTypes];

/**
 * DelegateMotionPayload
 */
export type DelegateMotionPayload = {
    type: Motions;
    debate_type?: DebateTypes | null;
    /**
     * Total Duration Minutes
     */
    total_duration_minutes?: number | null;
    /**
     * Per Speaker Seconds
     */
    per_speaker_seconds?: number | null;
    /**
     * Target Topic
     */
    target_topic?: string | null;
    /**
     * Details
     */
    details?: string | null;
};

/**
 * DelegateQuestionPayload
 */
export type DelegateQuestionPayload = {
    type: Questions;
    /**
     * Details
     */
    details?: string | null;
};

/**
 * DelegateVotingPayload
 */
export type DelegateVotingPayload = {
    vote: VotingChoice;
};

/**
 * DeleteAgendaItemEvent
 */
export type DeleteAgendaItemEvent = {
    /**
     * Type
     */
    type: 'DeleteAgendaItemEvent';
    payload: DeleteAgendaItemPayload;
};

/**
 * DeleteAgendaItemPayload
 */
export type DeleteAgendaItemPayload = {
    /**
     * Index
     */
    index: string;
};

/**
 * EmptyPayload
 */
export type EmptyPayload = {
    [key: string]: unknown;
};

/**
 * EndSpeechEvent
 */
export type EndSpeechEvent = {
    /**
     * Type
     */
    type: 'EndSpeechEvent';
    payload: EmptyPayload;
};

/**
 * FinishCaucusEvent
 */
export type FinishCaucusEvent = {
    /**
     * Type
     */
    type: 'FinishCaucusEvent';
    payload: EmptyPayload;
};

/**
 * GrantFloorEvent
 */
export type GrantFloorEvent = {
    /**
     * Type
     */
    type: 'GrantFloorEvent';
    payload: GrantFloorPayload;
};

/**
 * GrantFloorPayload
 */
export type GrantFloorPayload = {
    /**
     * Representation Id
     */
    representation_id: number;
    /**
     * Seconds
     */
    seconds?: number | null;
};

/**
 * IncreaseTimerEvent
 */
export type IncreaseTimerEvent = {
    /**
     * Type
     */
    type: 'IncreaseTimerEvent';
    payload: ChairIncreaseTimerPayload;
};

/**
 * JoinQueueEvent
 */
export type JoinQueueEvent = {
    /**
     * Type
     */
    type: 'JoinQueueEvent';
    /**
     * Payload
     */
    payload?: {
        [key: string]: unknown;
    };
};

/**
 * LeaveQueueEvent
 */
export type LeaveQueueEvent = {
    /**
     * Type
     */
    type: 'LeaveQueueEvent';
    /**
     * Payload
     */
    payload?: {
        [key: string]: unknown;
    };
};

/**
 * LogMotionEvent
 */
export type LogMotionEvent = {
    /**
     * Type
     */
    type: 'LogMotionEvent';
    payload: ChairMotionPayload;
};

/**
 * MajorityTypes
 */
export const MajorityTypes = {
    MAIORIA_SIMPLES: 'Maioria Simples',
    MAIORIA_QUALIFICADA: 'Maioria Qualificada',
    CONSENSO: 'Consenso'
} as const;

/**
 * MajorityTypes
 */
export type MajorityTypes = typeof MajorityTypes[keyof typeof MajorityTypes];

/**
 * MarkAgendaItemEvent
 */
export type MarkAgendaItemEvent = {
    /**
     * Type
     */
    type: 'MarkAgendaItemEvent';
    payload: MarkAgendaItemPayload;
};

/**
 * MarkAgendaItemPayload
 */
export type MarkAgendaItemPayload = {
    /**
     * Index
     */
    index: string;
    /**
     * Indiscussion
     */
    indiscussion?: boolean | null;
    /**
     * Discussed
     */
    discussed?: boolean | null;
};

/**
 * MarkRollCallBulkEvent
 */
export type MarkRollCallBulkEvent = {
    /**
     * Type
     */
    type: 'MarkRollCallBulkEvent';
    payload: MarkRollCallBulkPayload;
};

/**
 * MarkRollCallBulkPayload
 */
export type MarkRollCallBulkPayload = {
    /**
     * Rollcalls
     */
    Rollcalls: {
        [key: string]: RollCallChoice;
    };
};

/**
 * MarkRollCallEvent
 */
export type MarkRollCallEvent = {
    /**
     * Type
     */
    type: 'MarkRollCallEvent';
    payload: MarkRollCallPayload;
};

/**
 * MarkRollCallPayload
 */
export type MarkRollCallPayload = {
    /**
     * Delegation Id
     */
    delegation_id: number;
    choice: RollCallChoice;
};

/**
 * MotionDecision
 *
 * Tracks decision for LogMotionEvent for chair
 */
export const MotionDecision = { ACCEPT: 'Accept', DENY: 'Deny' } as const;

/**
 * MotionDecision
 *
 * Tracks decision for LogMotionEvent for chair
 */
export type MotionDecision = typeof MotionDecision[keyof typeof MotionDecision];

/**
 * Motions
 */
export const Motions = {
    MUDAR_TIPO_DE_DEBATE: 'Mudar Tipo de Debate',
    ADIAMENTO_DE_SESSÃO: 'Adiamento de Sessão',
    REABERTURA_DE_SESSÃO: 'Reabertura de Sessão',
    TOUR_DE_TABLE: 'Tour de Table',
    ENCERRAMENTO_DE_DEBATE: 'Encerramento de Debate',
    VOTAÇÃO_DE_EMENDA: 'Votação de Emenda',
    VOTAÇÃO_POR_CHAMADA: 'Votação por Chamada',
    FECHAMENTO_DA_LISTA_DE_DISCURSOS: 'Fechamento da Lista de Discursos',
    REABERTURA_DE_LISTA_DE_DISCURSOS: 'Reabertura de Lista de Discursos',
    DIVISÃO_DA_PROPOSTA: 'Divisão da Proposta',
    INTRODUÇÃO_DA_PROPOSTA_DE_RESOLUÇÃO: 'Introdução da Proposta de Resolução',
    INTRODUÇÃO_DA_PROPOSTA_DE_EMENDA: 'Introdução da Proposta de Emenda',
    MUDANÇA_DE_TÓPICO: 'Mudança de Tópico',
    CONTAGEM_DE_QUÓRUM: 'Contagem de Quórum',
    '': ''
} as const;

/**
 * Motions
 */
export type Motions = typeof Motions[keyof typeof Motions];

/**
 * NextSpeakerEvent
 */
export type NextSpeakerEvent = {
    /**
     * Type
     */
    type: 'NextSpeakerEvent';
    payload: EmptyPayload;
};

/**
 * OpenInformalVotingEvent
 */
export type OpenInformalVotingEvent = {
    /**
     * Type
     */
    type: 'OpenInformalVotingEvent';
    payload: ChairOpenInformalVotingPayload;
};

/**
 * OpenSessionEvent
 */
export type OpenSessionEvent = {
    /**
     * Type
     */
    type: 'OpenSessionEvent';
    payload: EmptyPayload;
};

/**
 * Questions
 */
export const Questions = {
    ORDEM: 'Ordem',
    QUESTÃO: 'Questão',
    PRIVILÉGIO_PESSOAL: 'Privilégio Pessoal'
} as const;

/**
 * Questions
 */
export type Questions = typeof Questions[keyof typeof Questions];

/**
 * ResolveMotionEvent
 */
export type ResolveMotionEvent = {
    /**
     * Type
     */
    type: 'ResolveMotionEvent';
    payload: ChairResolveMotionPayload;
};

/**
 * RollCallChoice
 */
export const RollCallChoice = {
    PRESENT: 'Present',
    PRESENT_AND_VOTING: 'Present and Voting',
    ABSENT: 'Absent'
} as const;

/**
 * RollCallChoice
 */
export type RollCallChoice = typeof RollCallChoice[keyof typeof RollCallChoice];

/**
 * SetAgendaEvent
 */
export type SetAgendaEvent = {
    /**
     * Type
     */
    type: 'SetAgenda';
    payload: ChairSetAgendaPayload;
};

/**
 * SetAgendaItemEvent
 */
export type SetAgendaItemEvent = {
    /**
     * Type
     */
    type: 'SetAgendaItemEvent';
    payload: SetAgendaItemPayload;
};

/**
 * SetAgendaItemPayload
 */
export type SetAgendaItemPayload = {
    /**
     * Index
     */
    index: string;
    /**
     * Topic
     */
    topic: string;
};

/**
 * SetPhaseEvent
 */
export type SetPhaseEvent = {
    /**
     * Type
     */
    type: 'SetPhaseEvent';
    payload: ChairSetPhasePayload;
};

/**
 * States
 */
export const States = {
    SETUP_ROOM: 'Setup Room',
    ROLL_CALL: 'Roll Call',
    INITIAL_DEBATE: 'Initial Debate',
    OPEN_GSL: 'Open GSL',
    CLOSED_GSL: 'Closed GSL',
    VOTING_PREPARATION: 'Voting Preparation',
    VOTING_PROCEDURES: 'Voting Procedures',
    FINISHED: 'Finished',
    MODERATED_CAUCUS: 'Moderated Caucus',
    UNMODERATED_CAUCUS: 'Unmoderated Caucus',
    TOUR_DE_TABLE: 'Tour de Table',
    VOTING_EXECUTION: 'Voting Execution',
    BETWEEN_DEBATES: 'Between Debates'
} as const;

/**
 * States
 */
export type States = typeof States[keyof typeof States];

/**
 * SubmitMotionEvent
 */
export type SubmitMotionEvent = {
    /**
     * Type
     */
    type: 'SubmitMotionEvent';
    payload: DelegateMotionPayload;
};

/**
 * SubmitQuestionEvent
 */
export type SubmitQuestionEvent = {
    /**
     * Type
     */
    type: 'SubmitQuestionEvent';
    payload: DelegateQuestionPayload;
};

/**
 * ToggleTimerEvent
 */
export type ToggleTimerEvent = {
    /**
     * Type
     */
    type: 'ToggleTimerEvent';
    payload: ChairToggleTimerPayload;
};

/**
 * VotingChoice
 */
export const VotingChoice = {
    FAVOUR: 'Favour',
    AGAINST: 'Against',
    ABSTAIN: 'Abstain',
    YES_WITH_RIGHTS: 'Yes With Rights',
    NO_WITH_RIGHTS: 'No With Rights',
    PASS: 'Pass'
} as const;

/**
 * VotingChoice
 */
export type VotingChoice = typeof VotingChoice[keyof typeof VotingChoice];

export type SessionEvent = ({
    type: 'SubmitMotionEvent';
} & SubmitMotionEvent) | ({
    type: 'SubmitQuestionEvent';
} & SubmitQuestionEvent) | ({
    type: 'CastVoteEvent';
} & CastVoteEvent) | ({
    type: 'AnswerRollCallEvent';
} & AnswerRollCallEvent) | ({
    type: 'JoinQueueEvent';
} & JoinQueueEvent) | ({
    type: 'LeaveQueueEvent';
} & LeaveQueueEvent) | ({
    type: 'LogMotionEvent';
} & LogMotionEvent) | ({
    type: 'OpenSessionEvent';
} & OpenSessionEvent) | ({
    type: 'CloseSessionEvent';
} & CloseSessionEvent) | ({
    type: 'IncreaseTimerEvent';
} & IncreaseTimerEvent) | ({
    type: 'ToggleTimerEvent';
} & ToggleTimerEvent) | ({
    type: 'OpenInformalVotingEvent';
} & OpenInformalVotingEvent) | ({
    type: 'CloseProceduralVotingEvent';
} & CloseProceduralVotingEvent) | ({
    type: 'CloseInformalVotingEvent';
} & CloseInformalVotingEvent) | ({
    type: 'FinishCaucusEvent';
} & FinishCaucusEvent) | ({
    type: 'ResolveMotionEvent';
} & ResolveMotionEvent) | ({
    type: 'NextSpeakerEvent';
} & NextSpeakerEvent) | ({
    type: 'AddGslSpeakerEvent';
} & AddGslSpeakerEvent) | ({
    type: 'GrantFloorEvent';
} & GrantFloorEvent) | ({
    type: 'CedeTimeEvent';
} & CedeTimeEvent) | ({
    type: 'EndSpeechEvent';
} & EndSpeechEvent) | ({
    type: 'SetAgenda';
} & SetAgendaEvent) | ({
    type: 'SetAgendaItemEvent';
} & SetAgendaItemEvent) | ({
    type: 'MarkAgendaItemEvent';
} & MarkAgendaItemEvent) | ({
    type: 'DeleteAgendaItemEvent';
} & DeleteAgendaItemEvent) | ({
    type: 'SetPhaseEvent';
} & SetPhaseEvent) | ({
    type: 'MarkRollCallEvent';
} & MarkRollCallEvent) | ({
    type: 'CloseRollCallEvent';
} & CloseRollCallEvent) | ({
    type: 'MarkRollCallBulkEvent';
} & MarkRollCallBulkEvent);

/**
 * AuthenticateMessage
 */
export type AuthenticateMessage = {
    /**
     * Type
     */
    type?: 'authenticate';
    /**
     * Access Token
     */
    access_token: string;
};

/**
 * EventMessage
 */
export type EventMessage = {
    /**
     * Type
     */
    type?: 'event';
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Event
     */
    event: ({
        type: 'SubmitMotionEvent';
    } & SubmitMotionEvent) | ({
        type: 'SubmitQuestionEvent';
    } & SubmitQuestionEvent) | ({
        type: 'CastVoteEvent';
    } & CastVoteEvent) | ({
        type: 'AnswerRollCallEvent';
    } & AnswerRollCallEvent) | ({
        type: 'JoinQueueEvent';
    } & JoinQueueEvent) | ({
        type: 'LeaveQueueEvent';
    } & LeaveQueueEvent) | ({
        type: 'LogMotionEvent';
    } & LogMotionEvent) | ({
        type: 'OpenSessionEvent';
    } & OpenSessionEvent) | ({
        type: 'CloseSessionEvent';
    } & CloseSessionEvent) | ({
        type: 'IncreaseTimerEvent';
    } & IncreaseTimerEvent) | ({
        type: 'ToggleTimerEvent';
    } & ToggleTimerEvent) | ({
        type: 'OpenInformalVotingEvent';
    } & OpenInformalVotingEvent) | ({
        type: 'CloseProceduralVotingEvent';
    } & CloseProceduralVotingEvent) | ({
        type: 'CloseInformalVotingEvent';
    } & CloseInformalVotingEvent) | ({
        type: 'FinishCaucusEvent';
    } & FinishCaucusEvent) | ({
        type: 'ResolveMotionEvent';
    } & ResolveMotionEvent) | ({
        type: 'NextSpeakerEvent';
    } & NextSpeakerEvent) | ({
        type: 'AddGslSpeakerEvent';
    } & AddGslSpeakerEvent) | ({
        type: 'GrantFloorEvent';
    } & GrantFloorEvent) | ({
        type: 'CedeTimeEvent';
    } & CedeTimeEvent) | ({
        type: 'EndSpeechEvent';
    } & EndSpeechEvent) | ({
        type: 'SetAgenda';
    } & SetAgendaEvent) | ({
        type: 'SetAgendaItemEvent';
    } & SetAgendaItemEvent) | ({
        type: 'MarkAgendaItemEvent';
    } & MarkAgendaItemEvent) | ({
        type: 'DeleteAgendaItemEvent';
    } & DeleteAgendaItemEvent) | ({
        type: 'SetPhaseEvent';
    } & SetPhaseEvent) | ({
        type: 'MarkRollCallEvent';
    } & MarkRollCallEvent) | ({
        type: 'CloseRollCallEvent';
    } & CloseRollCallEvent) | ({
        type: 'MarkRollCallBulkEvent';
    } & MarkRollCallBulkEvent);
};

export type ClientSessionMessage = ({
    type: 'authenticate';
} & AuthenticateMessage) | ({
    type: 'event';
} & EventMessage);

/**
 * AgendaItem
 */
export type AgendaItem = {
    /**
     * Index
     */
    index: string;
    /**
     * Topic
     */
    topic: string;
    /**
     * Already Discussed
     */
    already_discussed: boolean;
};

/**
 * DebateContext
 */
export type DebateContext = {
    debate_type: DebateTypes;
    return_state: States;
    /**
     * Total Duration Seconds
     */
    total_duration_seconds?: number | null;
    /**
     * Total Speeches
     */
    total_speeches?: number | null;
    /**
     * Per Speaker Seconds
     */
    per_speaker_seconds?: number | null;
    /**
     * Expires At
     */
    expires_at?: string | null;
    /**
     * Topic
     */
    topic?: string | null;
};

/**
 * DelegationContext
 */
export type DelegationContext = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Seat
     */
    seat: string;
    /**
     * Code
     */
    code: string;
};

/**
 * DispatchResultMessage
 */
export type DispatchResultMessage = {
    /**
     * Type
     */
    type?: 'dispatch_result';
    state: SessionLiveState;
    effect?: SessionEffect | null;
};

/**
 * EventErrorCode
 *
 * Code errors for invalid events
 */
export const EventErrorCode = {
    INVALID_MESSAGE: 'invalid_message',
    FORBIDDEN: 'forbidden',
    INVALID_STATE: 'invalid_state',
    NOT_FOUND: 'not_found',
    CONFLICT: 'conflict',
    INTERNAL_ERROR: 'internal_error'
} as const;

/**
 * EventErrorCode
 *
 * Code errors for invalid events
 */
export type EventErrorCode = typeof EventErrorCode[keyof typeof EventErrorCode];

/**
 * EventRejectedMessage
 */
export type EventRejectedMessage = {
    /**
     * Type
     */
    type?: 'event_rejected';
    /**
     * Request Id
     */
    request_id?: string | null;
    code: EventErrorCode;
    /**
     * Message
     */
    message: string;
};

/**
 * MotionContext
 */
export type MotionContext = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Priority
     */
    priority?: number;
    type: Motions;
    /**
     * Delegate Id
     */
    delegate_id?: number | null;
    /**
     * Timestamp
     */
    timestamp: string;
    debate_type?: DebateTypes | null;
    /**
     * Total Duration Minutes
     */
    total_duration_minutes?: number | null;
    /**
     * Per Speaker Seconds
     */
    per_speaker_seconds?: number | null;
    /**
     * Target Topic
     */
    target_topic?: string | null;
    /**
     * Details
     */
    details?: string | null;
};

/**
 * QuestionContext
 */
export type QuestionContext = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Priority
     */
    priority?: number;
    type: Questions;
    /**
     * Delegate Id
     */
    delegate_id?: number | null;
    /**
     * Details
     */
    details?: string | null;
};

/**
 * RollCallContext
 */
export type RollCallContext = {
    /**
     * Registry
     */
    registry?: {
        [key: string]: RollCallChoice;
    };
    return_state?: States | null;
};

/**
 * SessionEffect
 */
export type SessionEffect = {
    type: SessionEffectType;
    /**
     * Data
     */
    data?: {
        [key: string]: unknown;
    };
};

/**
 * SessionEffectType
 */
export const SessionEffectType = { VOTE_CLOSED: 'Vote Closed' } as const;

/**
 * SessionEffectType
 */
export type SessionEffectType = typeof SessionEffectType[keyof typeof SessionEffectType];

/**
 * SessionLiveState
 */
export type SessionLiveState = {
    /**
     * Session Id
     */
    session_id: number;
    /**
     * Start Time
     */
    start_time: string;
    /**
     * Delegations
     */
    delegations: {
        [key: string]: DelegationContext;
    };
    current_state?: States;
    /**
     * Timer Is Running
     */
    timer_is_running?: boolean;
    /**
     * Timer Expiration
     */
    timer_expiration?: string | null;
    /**
     * Timer Remaining Seconds
     */
    timer_remaining_seconds?: number;
    /**
     * Current Speaker
     */
    current_speaker?: number | null;
    /**
     * Gsl Queue
     */
    gsl_queue?: Array<number>;
    /**
     * Can Set Motion
     */
    can_set_motion?: boolean;
    /**
     * Gsl Default Time Seconds
     */
    gsl_default_time_seconds?: number;
    /**
     * Caucus List
     */
    caucus_list?: Array<number>;
    debate?: DebateContext | null;
    /**
     * Submitted Motions
     */
    submitted_motions?: Array<MotionContext>;
    /**
     * Submitted Questions
     */
    submitted_questions?: Array<QuestionContext>;
    /**
     * Agenda Topics
     */
    agenda_topics?: {
        [key: string]: AgendaItem;
    };
    /**
     * Active Topic Index
     */
    active_topic_index?: string | null;
    voting?: VotingContext | null;
    roll_call: RollCallContext;
    /**
     * Has Veto Power
     */
    has_veto_power?: boolean;
};

/**
 * StateSnapshotMessage
 */
export type StateSnapshotMessage = {
    /**
     * Type
     */
    type?: 'state_snapshot';
    state: SessionLiveState;
};

/**
 * VotingContext
 */
export type VotingContext = {
    target_type: VotingType;
    /**
     * Title
     */
    title?: string | null;
    return_state: States;
    /**
     * Voting Registry
     */
    voting_registry?: {
        [key: string]: VotingChoice;
    };
    majority?: MajorityTypes | null;
    motion_in_vote?: MotionContext | null;
    /**
     * Allow Veto Power
     */
    allow_veto_power?: boolean;
};

/**
 * VotingType
 */
export const VotingType = {
    INFORMAL: 'Informal',
    PROCEDURAL: 'Procedural',
    SUBSTANTIVE: 'Substantive'
} as const;

/**
 * VotingType
 */
export type VotingType = typeof VotingType[keyof typeof VotingType];

export type ServerSessionMessage = ({
    type: 'state_snapshot';
} & StateSnapshotMessage) | ({
    type: 'event_rejected';
} & EventRejectedMessage) | ({
    type: 'dispatch_result';
} & DispatchResultMessage);

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateSessionEndpointSessionsPostData = {
    body: SessionCreationSchema;
    path?: never;
    query?: never;
    url: '/sessions/';
};

export type CreateSessionEndpointSessionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSessionEndpointSessionsPostError = CreateSessionEndpointSessionsPostErrors[keyof CreateSessionEndpointSessionsPostErrors];

export type CreateSessionEndpointSessionsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ActivateSessionEndpointSessionsSessionIdActivatePostData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: number;
    };
    query?: never;
    url: '/sessions/{session_id}/activate';
};

export type ActivateSessionEndpointSessionsSessionIdActivatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ActivateSessionEndpointSessionsSessionIdActivatePostError = ActivateSessionEndpointSessionsSessionIdActivatePostErrors[keyof ActivateSessionEndpointSessionsSessionIdActivatePostErrors];

export type ActivateSessionEndpointSessionsSessionIdActivatePostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ActivateSessionEndpointSessionsSessionIdActivatePostResponse = ActivateSessionEndpointSessionsSessionIdActivatePostResponses[keyof ActivateSessionEndpointSessionsSessionIdActivatePostResponses];

export type GetMySessionAccessAccessSessionsSessionIdMeGetData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: number;
    };
    query?: never;
    url: '/access/sessions/{session_id}/me';
};

export type GetMySessionAccessAccessSessionsSessionIdMeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMySessionAccessAccessSessionsSessionIdMeGetError = GetMySessionAccessAccessSessionsSessionIdMeGetErrors[keyof GetMySessionAccessAccessSessionsSessionIdMeGetErrors];

export type GetMySessionAccessAccessSessionsSessionIdMeGetResponses = {
    /**
     * Successful Response
     */
    200: SessionRepresentation;
};

export type GetMySessionAccessAccessSessionsSessionIdMeGetResponse = GetMySessionAccessAccessSessionsSessionIdMeGetResponses[keyof GetMySessionAccessAccessSessionsSessionIdMeGetResponses];

export type GetMyConferenceAccessEndpointAccessConferencesConferenceIdMeGetData = {
    body?: never;
    path: {
        /**
         * Conference Id
         */
        conference_id: number;
    };
    query?: never;
    url: '/access/conferences/{conference_id}/me';
};

export type GetMyConferenceAccessEndpointAccessConferencesConferenceIdMeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMyConferenceAccessEndpointAccessConferencesConferenceIdMeGetError = GetMyConferenceAccessEndpointAccessConferencesConferenceIdMeGetErrors[keyof GetMyConferenceAccessEndpointAccessConferencesConferenceIdMeGetErrors];

export type GetMyConferenceAccessEndpointAccessConferencesConferenceIdMeGetResponses = {
    /**
     * Successful Response
     */
    200: ConferenceAccess;
};

export type GetMyConferenceAccessEndpointAccessConferencesConferenceIdMeGetResponse = GetMyConferenceAccessEndpointAccessConferencesConferenceIdMeGetResponses[keyof GetMyConferenceAccessEndpointAccessConferencesConferenceIdMeGetResponses];

export type ListConferencesEndpointConferencesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/conferences';
};

export type ListConferencesEndpointConferencesGetResponses = {
    /**
     * Response List Conferences Endpoint Conferences Get
     *
     * Successful Response
     */
    200: Array<ConferenceRead>;
};

export type ListConferencesEndpointConferencesGetResponse = ListConferencesEndpointConferencesGetResponses[keyof ListConferencesEndpointConferencesGetResponses];

export type CreateConferenceEndpointConferencesPostData = {
    body: ConferenceCreate;
    path?: never;
    query?: never;
    url: '/conferences';
};

export type CreateConferenceEndpointConferencesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateConferenceEndpointConferencesPostError = CreateConferenceEndpointConferencesPostErrors[keyof CreateConferenceEndpointConferencesPostErrors];

export type CreateConferenceEndpointConferencesPostResponses = {
    /**
     * Successful Response
     */
    201: ConferenceRead;
};

export type CreateConferenceEndpointConferencesPostResponse = CreateConferenceEndpointConferencesPostResponses[keyof CreateConferenceEndpointConferencesPostResponses];

export type GetConferenceEndpointConferencesConferenceIdGetData = {
    body?: never;
    path: {
        /**
         * Conference Id
         */
        conference_id: number;
    };
    query?: never;
    url: '/conferences/{conference_id}';
};

export type GetConferenceEndpointConferencesConferenceIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConferenceEndpointConferencesConferenceIdGetError = GetConferenceEndpointConferencesConferenceIdGetErrors[keyof GetConferenceEndpointConferencesConferenceIdGetErrors];

export type GetConferenceEndpointConferencesConferenceIdGetResponses = {
    /**
     * Successful Response
     */
    200: ConferenceRead;
};

export type GetConferenceEndpointConferencesConferenceIdGetResponse = GetConferenceEndpointConferencesConferenceIdGetResponses[keyof GetConferenceEndpointConferencesConferenceIdGetResponses];

export type ListCommitteesEndpointConferencesConferenceIdCommitteesGetData = {
    body?: never;
    path: {
        /**
         * Conference Id
         */
        conference_id: number;
    };
    query?: never;
    url: '/conferences/{conference_id}/committees';
};

export type ListCommitteesEndpointConferencesConferenceIdCommitteesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListCommitteesEndpointConferencesConferenceIdCommitteesGetError = ListCommitteesEndpointConferencesConferenceIdCommitteesGetErrors[keyof ListCommitteesEndpointConferencesConferenceIdCommitteesGetErrors];

export type ListCommitteesEndpointConferencesConferenceIdCommitteesGetResponses = {
    /**
     * Response List Committees Endpoint Conferences  Conference Id  Committees Get
     *
     * Successful Response
     */
    200: Array<CommitteeRead>;
};

export type ListCommitteesEndpointConferencesConferenceIdCommitteesGetResponse = ListCommitteesEndpointConferencesConferenceIdCommitteesGetResponses[keyof ListCommitteesEndpointConferencesConferenceIdCommitteesGetResponses];

export type CreateCommitteeEndpointConferencesConferenceIdCommitteesPostData = {
    body: CommitteeCreate;
    path: {
        /**
         * Conference Id
         */
        conference_id: number;
    };
    query?: never;
    url: '/conferences/{conference_id}/committees';
};

export type CreateCommitteeEndpointConferencesConferenceIdCommitteesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCommitteeEndpointConferencesConferenceIdCommitteesPostError = CreateCommitteeEndpointConferencesConferenceIdCommitteesPostErrors[keyof CreateCommitteeEndpointConferencesConferenceIdCommitteesPostErrors];

export type CreateCommitteeEndpointConferencesConferenceIdCommitteesPostResponses = {
    /**
     * Successful Response
     */
    201: CommitteeRead;
};

export type CreateCommitteeEndpointConferencesConferenceIdCommitteesPostResponse = CreateCommitteeEndpointConferencesConferenceIdCommitteesPostResponses[keyof CreateCommitteeEndpointConferencesConferenceIdCommitteesPostResponses];

export type GetCommitteeEndpointCommitteesCommitteeIdGetData = {
    body?: never;
    path: {
        /**
         * Committee Id
         */
        committee_id: number;
    };
    query?: never;
    url: '/committees/{committee_id}';
};

export type GetCommitteeEndpointCommitteesCommitteeIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCommitteeEndpointCommitteesCommitteeIdGetError = GetCommitteeEndpointCommitteesCommitteeIdGetErrors[keyof GetCommitteeEndpointCommitteesCommitteeIdGetErrors];

export type GetCommitteeEndpointCommitteesCommitteeIdGetResponses = {
    /**
     * Successful Response
     */
    200: CommitteeRead;
};

export type GetCommitteeEndpointCommitteesCommitteeIdGetResponse = GetCommitteeEndpointCommitteesCommitteeIdGetResponses[keyof GetCommitteeEndpointCommitteesCommitteeIdGetResponses];
